[package]
name = "maths"
version = "0.1.0"
edition = "2021"

[features]
short_hand_constructors = []
lhs_scalar_vec_ops = []
casts = []
default = ["short_hand_constructors", "lhs_scalar_vec_ops", "casts"]
